//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ancestry.Daisy.Tests.Component {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ancestry.Daisy.Tests.Component.Rules", typeof(Rules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has account
        ///    NOT
        ///        Balance is less than 0
        ///        OR Type is Checking.
        /// </summary>
        internal static string UserHasNonCheckingWithABalance {
            get {
                return ResourceManager.GetString("UserHasNonCheckingWithABalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active
        ///NOT Has Account
        ///    Has Transaction
        ///        Timestamp before 1 year ago
        ///        .
        /// </summary>
        internal static string UserHasNoRecentTransactions {
            get {
                return ResourceManager.GetString("UserHasNoRecentTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has account
        ///    NOT has transactions.
        /// </summary>
        internal static string UserHasUnusedAccount {
            get {
                return ResourceManager.GetString("UserHasUnusedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active
        ///Has Account
        ///    Type is MoneyMarket
        ///    NOT Has Transaction.
        /// </summary>
        internal static string UserHasUnusedMoneyMarket {
            get {
                return ResourceManager.GetString("UserHasUnusedMoneyMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active
        ///Has Account
        ///    Type is checking
        ///    Balance is less than 0.
        /// </summary>
        internal static string UserIsOverdrawnOnChecking {
            get {
                return ResourceManager.GetString("UserIsOverdrawnOnChecking", resourceCulture);
            }
        }
    }
}
